<?xml version="1.0" encoding="UTF-8"?>
<project name="Eq_Nexum_Proyecto" default="run" basedir=".">
    <property name="src.dir" value="src"/>
    <property name="build.dir" value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${classes.dir}"/>
        <javac srcdir="${src.dir}" destdir="${classes.dir}" includeantruntime="false" encoding="UTF-8"/>
    </target>

    <target name="run" depends="compile">
        <java classname="controlador.Main" classpath="${classes.dir}" fork="true"/>
    </target>
</project>
